/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'earlzero' at '16.07.16 20:54' with Gradle 2.10
 *
 * @author earlzero, @date 16.07.16 20:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
